CFLAGS=-Wall -g

allRocks: cleanRocks rocks

cleanRocks:
	rm -rf rocks

allTestScanf: cleanTestScanf testScanf

cleanTestScanf:
	rm -rf testScanf

allCodeMagnets: cleanCodeMagnets codeMagnets

cleanCodeMagnets:
	rm -rf codeMagnets

allCards: cleanCards cards

cleanCards:
	rm -rf cards
