price_drinks.o: price_drinks.c
	gcc -Wall -g -c price_drinks.c

price_drinks: price_drinks.o
	gcc price_drinks.o -o price_drinks

print_ints.o: print_ints.c
	gcc -Wall -g -c print_ints.c

print_ints: print_ints.o
	gcc print_ints.o -o print_ints
