coffee.o: coffee.c
	gcc -Wall -g -c coffee.c -o coffee.o

coffee: coffee.o
	gcc coffee.o -o coffee

test_coffee.o: test_coffee.c
	gcc -Wall -g -c test_coffee.c -o test_coffee.o

test_coffee: test_coffee.o
	gcc test_coffee.o -o test_coffee
